<?php
/**
 * @copyright Copyright © Avarda. All rights reserved.
 * @package   Avarda_Checkout3
 */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $block \Avarda\Checkout3\Block\Checkout */
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script>
        const CHECKOUT3_JS_BUNDLE = '<?= $block->getCheckOutClientScriptPath(); ?>';
        (function(e,t,n,a,s,c,o,i,r){e[a]=e[a]||function(){(e[a].q=e[a].q||[
        ]).push(arguments)};e[a].i=s;i=t.createElement(n);i.async=1
        ;i.src=o+"?v="+c+"&ts="+1*new Date;r=t.getElementsByTagName(n)[0]
        ;r.parentNode.insertBefore(i,r)})(window,document,"script",
            "avardaCheckoutInit","avardaCheckout","1.0.0",CHECKOUT3_JS_BUNDLE
        );
    </script>
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        var options = {
            disableFocus: true,
            rootElementId: "avarda-checkout-iframe",
            redirectUrlBase: '<?= $escaper->escapeUrl($block->getCallbackUrl()) ?>',
            saveOrderUrl: '<?= $escaper->escapeUrl($block->getSaveOrderUrl()) ?>',
            showPostcode: !!<?= $block->getShowPostcode() ? 1 : 0 ?>,
            addressChangeCallback: !!<?= $block->getAdressChangeCallback() ? 1 : 0 ?>,
            offerLogin: !!<?= $block->getOfferLogin() ? 1 : 0 ?>,
            redirectUrl: '',
            styles: <?= $block->getStyles() ?>
        };
        window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        window.checkoutConfig.checkoutUrl = '<?= $escaper->escapeUrl($block->getCheckoutUrl()) ?>';
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
</div>
