name: Unit tests

on:
  push:
    branches: [ dev, master, main ]
  pull_request:

env:
  COMPOSER_AUTH: '{"http-basic":{"repo.magento.com":{"username":"${{ secrets.MAGENTO_PUBLIC_KEY }}","password":"${{ secrets.MAGENTO_PRIVATE_KEY }}"}}}'

jobs:
  unit-php82:
    name: Unit tests (PHP 8.2, Magento 2.4.7-p10)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-unit-tests/8.2@master
        env:
          MAGENTO_VERSION: '2.4.7-p10'
          MODULE_NAME: Avarda_Checkout3
          COMPOSER_NAME: avarda/checkout3

  unit-php83:
    name: Unit tests (PHP 8.3, Magento 2.4.8-p5)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-unit-tests/8.3@master
        env:
          MAGENTO_VERSION: '2.4.8-p5'
          MODULE_NAME: Avarda_Checkout3
          COMPOSER_NAME: avarda/checkout3
